# Generated by Django 2.1.12 on 2019-09-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='anser',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
